---
- name: Ensure Crossplane motd banner is present
  ansible.builtin.copy:
    src: 99-crossplane
    dest: '{{ destination }}/{{ priority }}-crossplane'
    mode: 0755
  when: ansible_provider_meta.ansiblerun.state == 'present'
  notify: 'update motd'

- name: Ensure Crossplane motd banner is absent
  ansible.builtin.file:
    path: '{{ destination }}/{{ priority }}-crossplane'
    state: absent
  when: ansible_provider_meta.ansiblerun.state == 'absent'
  notify: 'update motd'
